name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test --package tidos --tests --verbose
          cargo test -p tidos --features "i18n,rocket,axum,actix-web,warp" --test i18n --verbose

  publish:
    name: Publish to crates.io
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p tidos_macro --verbose
          cargo publish -p tidos_i18n --verbose
          sleep 60
          cargo publish -p tidos --verbose
